/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Projeto_Ludo.View;

import java.net.InetAddress;
import java.net.UnknownHostException;
import javax.swing.JOptionPane;

/**
 *
 * @author Henrique
 */
public class Janela_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Janela_Principal
     */
    public Janela_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanelFundo = new javax.swing.JPanel();
        jButtonConectar = new javax.swing.JButton();
        jButtonSerHost = new javax.swing.JButton();
        jButtonRegras = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jLabelNomeJogo = new javax.swing.JLabel();
        jPanelFundoTitulo = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelFundo.setBackground(new java.awt.Color(153, 153, 153));
        jPanelFundo.setForeground(new java.awt.Color(153, 153, 153));

        jButtonConectar.setFont(new java.awt.Font("Blue Fonte Sans", 0, 24)); // NOI18N
        jButtonConectar.setText("Conectar");
        jButtonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConectarActionPerformed(evt);
            }
        });

        jButtonSerHost.setFont(new java.awt.Font("Blue Fonte Sans", 0, 24)); // NOI18N
        jButtonSerHost.setText("Ser Host");
        jButtonSerHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSerHostActionPerformed(evt);
            }
        });

        jButtonRegras.setFont(new java.awt.Font("Blue Fonte Sans", 0, 24)); // NOI18N
        jButtonRegras.setText("Regras");
        jButtonRegras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegrasActionPerformed(evt);
            }
        });

        jButtonSair.setFont(new java.awt.Font("Blue Fonte Sans", 0, 24)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jLabelNomeJogo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelNomeJogo.setFont(new java.awt.Font("Blue Fonte Sans", 0, 80)); // NOI18N
        jLabelNomeJogo.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNomeJogo.setText("    LUDO");

        javax.swing.GroupLayout jPanelFundoLayout = new javax.swing.GroupLayout(jPanelFundo);
        jPanelFundo.setLayout(jPanelFundoLayout);
        jPanelFundoLayout.setHorizontalGroup(
            jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoLayout.createSequentialGroup()
                .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFundoLayout.createSequentialGroup()
                        .addGap(340, 340, 340)
                        .addGroup(jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRegras, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSerHost, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelFundoLayout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jLabelNomeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 635, Short.MAX_VALUE))
        );
        jPanelFundoLayout.setVerticalGroup(
            jPanelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFundoLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabelNomeJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(jButtonConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSerHost, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRegras, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(271, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelFundoTituloLayout = new javax.swing.GroupLayout(jPanelFundoTitulo);
        jPanelFundoTitulo.setLayout(jPanelFundoTituloLayout);
        jPanelFundoTituloLayout.setHorizontalGroup(
            jPanelFundoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 191, Short.MAX_VALUE)
        );
        jPanelFundoTituloLayout.setVerticalGroup(
            jPanelFundoTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(550, 550, 550)
                    .addComponent(jPanelFundoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(550, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(349, 349, 349)
                    .addComponent(jPanelFundoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(370, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRegrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegrasActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Regras:\n\nObjetivo do jogo\n" +
            "Percorrer o trajeto do tabuleiro com todas as peças e ser o primeiro jogador a chegar a casa central.\n" +
            "Regras\n" +
            "Para se iniciar a partida, joga-se o dado e o participante que fizer o maior número de pontos inicia o\n" +
            "jogo, continuando as jogadas em sentido horário.\n" +
            "Joga-se com um dado e os avanços são feitos de acordo com os pontos obtidos com o lançamento\n" +
            "dos dados.\n" +
            "Cada jogador lança o dado e se tirar “ 1” ou “6” poderá sair da casa de partida, sendo que, ao tirar\n" +
            "“6” você tem o direito de jogar o dado novamente.\n" +
            "Pode ser jogado por 2, 3 ou 4 jogadores (no caso de 4, é possível formar 2 duplas). O tabuleiro\n" +
            "quadrado tem um percurso em forma de cruz e cada jogador tem quatro peões. Um dado define os\n" +
            "movimentos.\n" +
            "Os peões de cada jogador começam na base de mesma cor. O objetivo do jogo é ser o primeiro a\n" +
            "levar seus 4 peões a dar uma volta no tabuleiro e a chegar no ponto final marcado com sua cor. Os\n" +
            "peões movem-se pelo percurso no sentido horário.\n" +
            "Para transportar um peão de sua base para seu ponto de partida é necessário tirar 6. Quando o\n" +
            "jogador já tem pelo menos um peão no percurso, ele pode mover o peão do número de casas tirado\n" +
            "no dado. Se tirar 6, além de usar esse resultado ele pode jogar novamente o dado.\n" +
            "Se um jogador chegar a uma casa já ocupada por um peão adversário, o peão adversário deve\n" +
            "voltar para sua base. Mas se 2 peões da mesma cor ocuparem uma mesma casa, eles não podem\n" +
            "ser capturados e nenhum adversário pode passar por essa casa, tendo seus peões bloqueados.\n" +
            "Após dar a volta no tabuleiro o peão avança pela reta final, de sua própria cor. A chegada ao ponto\n" +
            "final só pode ser obtida por um número exato nos dados. Se o jogador tirar mais do que o\n" +
            "necessário, ele vai até o fim e volta, tendo que aguardar sua próxima jogada. O vencedor é o\n" +
            "primeiro a levar seus quatro peões ao ponto de chegada da sua cor.\n" +
            "Nos Estados Unidos uma variante mais moderna do ludo tornou-se muito popular. O jogo Sorry (no\n" +
            "Brasil lançado em 1999 pela Estrela como Chispa), onde os dados foram substituídos por um\n" +
            "baralho de cartas, que traz algumas possibilidades novas", "Regras do Ludo", -1);
    }//GEN-LAST:event_jButtonRegrasActionPerformed

    private void jButtonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConectarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConectarActionPerformed

    private void jButtonSerHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSerHostActionPerformed
        // TODO add your handling code here:
        jSerHost frame = new jSerHost();
        
        
        frame.setVisible(true);
        frame.setSize(1000,870);
        dispose();
        frame.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButtonSerHostActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela_Principal().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConectar;
    private javax.swing.JButton jButtonRegras;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSerHost;
    private javax.swing.JLabel jLabelNomeJogo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanelFundo;
    private javax.swing.JPanel jPanelFundoTitulo;
    // End of variables declaration//GEN-END:variables

}
