/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Projeto_Ludo.View;

import java.net.InetAddress;
import java.net.UnknownHostException;
import javax.swing.JOptionPane;

/**
 *
 * @author Henrique
 */
public class Janela_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Janela_Principal
     */
    public Janela_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuJogarSerHost = new javax.swing.JMenu();
        jMenuItemSerHost = new javax.swing.JMenuItem();
        jMenuItemConectar = new javax.swing.JMenuItem();
        jMenuRegras = new javax.swing.JMenu();
        jMenuItemRegras = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("oi");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(492, 492, 492)
                .addComponent(jButton1)
                .addContainerGap(493, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jButton1)
                .addContainerGap(404, Short.MAX_VALUE))
        );

        jMenuJogarSerHost.setText("Jogar");

        jMenuItemSerHost.setText("Ser Host");
        jMenuJogarSerHost.add(jMenuItemSerHost);

        jMenuItemConectar.setText("Conectar");
        jMenuItemConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConectarActionPerformed(evt);
            }
        });
        jMenuJogarSerHost.add(jMenuItemConectar);

        jMenuBar1.add(jMenuJogarSerHost);

        jMenuRegras.setText("Regras");

        jMenuItemRegras.setText("Regras");
        jMenuItemRegras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemRegrasActionPerformed(evt);
            }
        });
        jMenuRegras.add(jMenuItemRegras);

        jMenuBar1.add(jMenuRegras);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemRegrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRegrasActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, "Regras:\n\nObjetivo do jogo\n" +
"Percorrer o trajeto do tabuleiro com todas as peças e ser o primeiro jogador a chegar a casa central.\n" +
"Regras\n" +
"Para se iniciar a partida, joga-se o dado e o participante que fizer o maior número de pontos inicia o\n" +
"jogo, continuando as jogadas em sentido horário.\n" +
"Joga-se com um dado e os avanços são feitos de acordo com os pontos obtidos com o lançamento\n" +
"dos dados.\n" +
"Cada jogador lança o dado e se tirar “ 1” ou “6” poderá sair da casa de partida, sendo que, ao tirar\n" +
"“6” você tem o direito de jogar o dado novamente.\n" +
"Pode ser jogado por 2, 3 ou 4 jogadores (no caso de 4, é possível formar 2 duplas). O tabuleiro\n" +
"quadrado tem um percurso em forma de cruz e cada jogador tem quatro peões. Um dado define os\n" +
"movimentos.\n" +
"Os peões de cada jogador começam na base de mesma cor. O objetivo do jogo é ser o primeiro a\n" +
"levar seus 4 peões a dar uma volta no tabuleiro e a chegar no ponto final marcado com sua cor. Os\n" +
"peões movem-se pelo percurso no sentido horário.\n" +
"Para transportar um peão de sua base para seu ponto de partida é necessário tirar 6. Quando o\n" +
"jogador já tem pelo menos um peão no percurso, ele pode mover o peão do número de casas tirado\n" +
"no dado. Se tirar 6, além de usar esse resultado ele pode jogar novamente o dado.\n" +
"Se um jogador chegar a uma casa já ocupada por um peão adversário, o peão adversário deve\n" +
"voltar para sua base. Mas se 2 peões da mesma cor ocuparem uma mesma casa, eles não podem\n" +
"ser capturados e nenhum adversário pode passar por essa casa, tendo seus peões bloqueados.\n" +
"Após dar a volta no tabuleiro o peão avança pela reta final, de sua própria cor. A chegada ao ponto\n" +
"final só pode ser obtida por um número exato nos dados. Se o jogador tirar mais do que o\n" +
"necessário, ele vai até o fim e volta, tendo que aguardar sua próxima jogada. O vencedor é o\n" +
"primeiro a levar seus quatro peões ao ponto de chegada da sua cor.\n" +
"Nos Estados Unidos uma variante mais moderna do ludo tornou-se muito popular. O jogo Sorry (no\n" +
"Brasil lançado em 1999 pela Estrela como Chispa), onde os dados foram substituídos por um\n" +
"baralho de cartas, que traz algumas possibilidades novas", "Regras do Ludo", -1);
    }//GEN-LAST:event_jMenuItemRegrasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText(jTextArea1.getText() + " Serafim");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItemConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConectarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, );
    }//GEN-LAST:event_jMenuItemConectarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela_Principal().setVisible(true);
            }
        });
    }
    
    public void PegarIP() throws UnknownHostException{
        String ipDaMaquina = InetAddress.getLocalHost().getHostAddress();
        System.out.println(ipDaMaquina);       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItemConectar;
    private javax.swing.JMenuItem jMenuItemRegras;
    private javax.swing.JMenuItem jMenuItemSerHost;
    private javax.swing.JMenu jMenuJogarSerHost;
    private javax.swing.JMenu jMenuRegras;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
